import React, { useEffect, useState } from 'react';
import { AlertTriangle, ArrowLeft, ArrowRight, CheckCircle2, Pause, Play, ShieldCheck, Terminal, Wrench } from 'lucide-react';

const slides = [
  { kicker: 'ACADEMIC SECURITY REPORT', title: 'การประยุกต์ใช้ AI & Model Context Protocol (MCP) กับการตรวจสอบ JRE 2027', body: 'รายงานฉบับนี้ใช้หลักฐานจากซอร์สในเครื่อง, production HTTP read-only, Supabase metadata, staging RLS verification และ dependency audit เพื่อแยกสิ่งที่ตรวจยืนยันได้ออกจากสิ่งที่ยังต้องทำต่อ', type: 'cover' },
  { kicker: '01 · SCOPE & METHOD', title: 'ขอบเขตและวิธีตรวจที่ทำจริง', body: 'ตรวจเว็บของเจ้าของระบบเท่านั้น โดยไม่ทดลองรหัสผ่านจริง ไม่แก้/ลบข้อมูล production และไม่ส่งข้อมูลส่วนตัวออกนอกระบบ', type: 'method' },
  { kicker: '02 · ARCHITECTURE', title: 'สถาปัตยกรรมเครื่องมือและเป้าหมาย', body: 'ภาพนี้เป็น diagram ที่ผู้ใช้แนบมา ใช้เพื่ออธิบายความสัมพันธ์ของ Kali, Burp, DVWA, MCP, AI และ JRE 2027; สถานะการติดตั้งจริงแสดงในสไลด์ท้าย', type: 'architecture' },
  { kicker: '03 · SEQUENCE', title: 'ลำดับการทำงานของ MCP audit', body: 'MCP ทำหน้าที่เป็น tool/context layer ไม่ใช่ตัวรับรองว่าช่องโหว่ถูกแก้แล้ว ทุกผลต้องตรวจซ้ำด้วย build, HTTP และ database policy', type: 'sequence' },
  { kicker: '04 · STAGING RLS', title: 'รัน RLS hardening บน staging สำเร็จ', body: 'หลังเจ้าของระบบยืนยัน ได้รัน supabase_security_hardening_staging.sql เฉพาะ project staging และตรวจซ้ำด้วย pg_policies กับ role anon โดยไม่แตะ production', type: 'staging' },
  { kicker: '05 · BURP EVIDENCE', title: 'หลักฐานการใช้ Burp Suite แบบ passive', body: 'ส่ง safe GET/OPTIONS ผ่าน Burp listener 127.0.0.1:8080 จำนวน 11 requests เพื่อเก็บ HTTP headers, status และ static assets; ภาพหลัง traffic แสดง 50 site-map items และ 13 responses processed โดยไม่ใช้ credential หรือ active scan', type: 'burp' },
  { kicker: '06 · FINDINGS', title: 'สรุปประเด็นจากหลักฐาน', body: 'พบ 10 ประเด็นที่ต้องแก้: Critical 3, High 5, Medium 1 และ Low 1 โดยประเด็นหนักสุดคือ public user_accounts/RLS และ magic OTP', type: 'findings' },
  { kicker: '07 · VERIFIED CONTROLS', title: 'สิ่งที่ยืนยันได้แล้ว กับสิ่งที่ยังไม่ใช่การปิดช่องโหว่', body: 'บาง control ทำงานจริง เช่น headers, API method handling และ staging RLS policy แต่ยังไม่เพียงพอจะสรุปว่า production ปลอดภัยทั้งหมด', type: 'controls' },
  { kicker: '08 · OWASP / CWE', title: 'การแมปความเสี่ยงเชิงวิชาการ', body: 'ใช้ CWE เป็นภาษากลางในการอธิบายผลกระทบและ remediation โดยไม่กำหนด CVSS ตัวเลขที่ยังไม่มี exploitability evidence ครบ', type: 'mapping' },
  { kicker: '09 · REMEDIATION', title: 'แผนแก้ไขและวิธีพิสูจน์ผล', body: 'แก้จาก data exposure → auth → RLS → dependency → regression test แล้วค่อย deploy', type: 'remediation' },
  { kicker: '10 · DEMO CHECKLIST', title: 'สคริปต์นำเสนออาจารย์แบบตรวจสอบได้', body: 'เปิดหน้าเว็บ, แสดงหลักฐาน build/npm audit/Burp, สาธิต diagram, อ่านผล staging RLS, อ่าน finding สำคัญ และชี้ข้อจำกัดอย่างตรงไปตรงมา', type: 'checklist' }
];

export default function AcademicPresentationSection({ onSwitchToAudit, onNavigateHome }) {
  const [index, setIndex] = useState(0);
  const [autoPlay, setAutoPlay] = useState(false);
  const slide = slides[index];

  useEffect(() => {
    if (!autoPlay) return undefined;
    const timer = setInterval(() => setIndex((current) => (current + 1) % slides.length), 8000);
    return () => clearInterval(timer);
  }, [autoPlay]);

  const next = () => setIndex((current) => (current + 1) % slides.length);
  const previous = () => setIndex((current) => (current - 1 + slides.length) % slides.length);

  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950/70 to-slate-900 border-2 border-indigo-500/40 p-6 sm:p-10 shadow-2xl"><div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6"><div className="space-y-3"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/15 text-indigo-200 border border-indigo-400/40 text-xs font-black tracking-wider">ACADEMIC RESEARCH DEFENSE</div><h1 className="text-2xl sm:text-4xl font-black text-white leading-tight">การประยุกต์ใช้ AI & MCP กับความมั่นคงปลอดภัยเว็บ JRE 2027</h1><p className="text-slate-300 text-xs sm:text-sm max-w-3xl leading-relaxed">หน้า presentation สำหรับอาจารย์: ผลตรวจปัจจุบันใช้หลักฐานจริงและประกาศข้อจำกัดของเครื่องมืออย่างชัดเจน</p><div className="flex flex-wrap gap-2 text-[11px]"><span className="px-2.5 py-1 rounded-lg bg-rose-500/15 text-rose-200 border border-rose-500/30">10 findings ต้องแก้</span><span className="px-2.5 py-1 rounded-lg bg-emerald-500/15 text-emerald-200 border border-emerald-500/30">Build ผ่าน</span><span className="px-2.5 py-1 rounded-lg bg-amber-500/15 text-amber-200 border border-amber-500/30">npm audit high 6</span></div></div><div className="p-5 rounded-2xl bg-slate-950/90 border border-indigo-500/30 text-center w-full lg:w-56"><div className="text-4xl font-black text-indigo-200">{index + 1}/{slides.length}</div><div className="text-xs text-slate-400 mt-1">สไลด์นำเสนอสด</div></div></div></section>
    <section className="flex flex-col sm:flex-row items-center justify-between gap-3 bg-slate-900 border border-slate-800 p-3 rounded-2xl"><div className="flex items-center gap-2"><button onClick={previous} className="p-2 rounded-xl bg-slate-800 text-white hover:bg-slate-700" aria-label="สไลด์ก่อนหน้า"><ArrowLeft className="w-4 h-4" /></button><button onClick={next} className="p-2 rounded-xl bg-indigo-600 text-white hover:bg-indigo-500" aria-label="สไลด์ถัดไป"><ArrowRight className="w-4 h-4" /></button><button onClick={() => setAutoPlay((value) => !value)} className="px-3 py-2 rounded-xl bg-slate-800 text-xs font-bold text-slate-200 flex items-center gap-1.5">{autoPlay ? <Pause className="w-3.5 h-3.5" /> : <Play className="w-3.5 h-3.5" />} {autoPlay ? 'หยุดอัตโนมัติ' : 'เล่นอัตโนมัติ'}</button></div><div className="flex flex-wrap gap-1.5 justify-center">{slides.map((item, slideIndex) => <button key={item.kicker} onClick={() => setIndex(slideIndex)} className={`w-7 h-7 rounded-lg text-[10px] font-black ${index === slideIndex ? 'bg-indigo-600 text-white' : 'bg-slate-800 text-slate-500 hover:text-white'}`} aria-label={`สไลด์ที่ ${slideIndex + 1}`}>{slideIndex + 1}</button>)}</div></section>
    <section className="p-6 sm:p-9 rounded-3xl bg-slate-900 border border-slate-800 shadow-2xl min-h-[520px]"><div className="flex items-center gap-2 text-xs font-black tracking-wider text-indigo-300"><span className="w-2.5 h-2.5 rounded-full bg-indigo-400" /> {slide.kicker}</div><h2 className="text-xl sm:text-3xl font-black text-white mt-3">{slide.title}</h2><p className="text-slate-300 text-sm leading-relaxed max-w-4xl mt-2">{slide.body}</p><div className="mt-7">{renderSlide(slide.type, { onSwitchToAudit })}</div></section>
    <section className="flex flex-wrap justify-between gap-2 text-xs"><div className="flex gap-2"><button onClick={onNavigateHome} className="px-3 py-2 rounded-xl bg-slate-800 text-slate-200 font-bold flex items-center gap-1.5"><ArrowLeft className="w-3.5 h-3.5" /> กลับหน้าหลัก</button><button onClick={onSwitchToAudit} className="px-3 py-2 rounded-xl bg-rose-700 text-white font-bold flex items-center gap-1.5"><ShieldCheck className="w-3.5 h-3.5" /> ดู findings แบบละเอียด</button></div><a href="/SECURITY_AUDIT_REPORT.md" className="px-3 py-2 rounded-xl border border-slate-700 text-slate-300 font-bold" target="_blank" rel="noopener noreferrer">ดาวน์โหลด Markdown Report</a></section>
  </div>;
}

function renderSlide(type, { onSwitchToAudit }) {
  if (type === 'cover') return <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Highlight icon="🎯" title="วัตถุประสงค์" text="ตรวจเว็บของเจ้าของระบบเพื่อหาจุดที่ต้อง harden และทำหลักฐานสำหรับการนำเสนอ" /><Highlight icon="🔎" title="หลักฐาน" text="Source review + build + npm audit + production HTTP + Supabase metadata" /><Highlight icon="🧭" title="หลักคิด" text="แยก verified controls, open findings และ limitations ไม่สรุปเกินหลักฐาน" /></div>;
  if (type === 'method') return <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Highlight icon="1" title="Local SAST" text="อ่าน source, SQL policy, auth flow และ data flow โดยไม่แสดง secrets/PII" /><Highlight icon="2" title="Safe DAST" text="GET/OPTIONS/method/header checks; ไม่ส่ง destructive payload หรือ credential จริง" /><Highlight icon="3" title="Dependency" text="npm run build ผ่าน; npm audit JSON พบ 10 รายการ" /><Highlight icon="4" title="Tool status" text="Burp listener รับ safe traffic 11 requests; UI crawl 50 items / 13 responses · Claude Desktop + MCP config พร้อม · Kali/WSL ต้องใช้ Admin · DVWA ยังไม่ติดตั้ง" /></div>;
  if (type === 'architecture') return <div className="space-y-3"><img src="/images/security/security-architecture.svg" alt="ภาพสถาปัตยกรรมการตรวจสอบความปลอดภัย" className="w-full rounded-2xl border border-slate-700 bg-slate-950" /><p className="text-xs text-amber-200 bg-amber-950/30 border border-amber-500/30 rounded-xl p-3">หมายเหตุ: diagram เป็นภาพอธิบาย workflow ที่แนบมา ไม่ใช่หลักฐานว่าทุกเครื่องมือในภาพถูกใช้ครบในการตรวจรอบนี้</p></div>;
  if (type === 'sequence') return <div className="space-y-3"><img src="/images/security/mcp-audit-sequence.svg" alt="ภาพลำดับการตรวจสอบผ่าน MCP" className="w-full rounded-2xl border border-slate-700 bg-slate-950" /><p className="text-xs text-slate-400">MCP ที่ตั้งค่าให้ Claude Desktop จำกัด path อยู่ที่โฟลเดอร์โปรเจกต์ การส่ง context ที่มี credential ต้องทำโดยผู้วิจัยอย่างระมัดระวังและควร redact ก่อนทุกครั้ง</p></div>;
  if (type === 'staging') return <div className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Highlight icon="1" title="Target" text="developer... Project · ref cksilfcjireystyludav · staging main" /><Highlight icon="2" title="Result" text="SQL Editor: Success. No rows returned · policy ใหม่ 8 รายการ" /><Highlight icon="3" title="Anon test" text="registrations 0 · project_settings forms_config เท่านั้น · announcements 0" /></div><div className="p-4 rounded-2xl bg-amber-950/30 border border-amber-500/30 text-xs text-amber-100 leading-relaxed">ขอบเขตสำคัญ: ผลนี้เป็น staging-only ไม่ใช่ production fix; ต้องทดสอบ authenticated owner/admin และย้าย password auth ไป Supabase Auth/server-side KDF ต่อ</div></div>;
  if (type === 'burp') return <div className="space-y-3"><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><img src="/images/security/burp-passive-crawl-before.png" alt="ภาพ Burp Suite passive crawl ก่อนส่ง traffic" className="w-full h-64 object-contain rounded-2xl border border-slate-700 bg-white" /><img src="/images/security/burp-passive-crawl-after.png" alt="ภาพ Burp Suite passive crawl หลังส่ง traffic" className="w-full h-64 object-contain rounded-2xl border border-slate-700 bg-white" /></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Highlight icon="1" title="Listener" text="127.0.0.1:8080 · HTTP /security ได้ 308 ไป HTTPS" /><Highlight icon="2" title="Traffic" text="scripted safe GET/OPTIONS 11 requests · UI crawl 50 items / 13 responses" /><Highlight icon="3" title="ข้อจำกัด" text="Passive เท่านั้น ไม่ลองรหัสผ่านหรือ active scan" /></div></div>;
  if (type === 'findings') return <div className="space-y-4"><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Stat label="Critical" value="3" tone="rose" /><Stat label="High" value="5" tone="orange" /><Stat label="Medium" value="1" tone="amber" /><Stat label="Low" value="1" tone="sky" /></div><div className="p-4 rounded-2xl bg-rose-950/20 border border-rose-500/30 text-sm text-rose-100 leading-relaxed"><strong>ประเด็นเร่งด่วน:</strong> public user_accounts/RLS policy, magic OTP, และ query registrations ทั้งตาราง หากจะสาธิตให้ใช้อินสแตนซ์ staging พร้อมข้อมูลจำลอง</div><button onClick={onSwitchToAudit} className="px-4 py-2 rounded-xl bg-rose-700 text-white text-xs font-black">เปิดรายละเอียด F-01 ถึง F-10</button></div>;
  if (type === 'controls') return <div className="grid grid-cols-1 md:grid-cols-2 gap-3">{['Build exit 0', 'Security headers ตอบจริง', 'Admin API method handling', 'CORS preflight ไม่สะท้อน evil origin', 'File API missing-id guard', 'security.txt/robots.txt เปิดอ่านได้', 'Staging RLS migration + anon visibility test ผ่าน', 'Burp proxy safe GET/OPTIONS 11 requests · UI crawl 50 items / 13 responses'].map((item) => <div key={item} className="p-4 rounded-2xl bg-emerald-950/20 border border-emerald-500/30 flex items-center gap-2 text-sm text-emerald-100"><CheckCircle2 className="w-4 h-4 text-emerald-400" />{item}</div>)}<div className="md:col-span-2 p-4 rounded-2xl bg-amber-950/20 border border-amber-500/30 text-xs text-amber-100">Verified control ไม่เท่ากับ vulnerability resolved: production RLS, auth data model, dependency และ OTP ยังต้องแก้/ทดสอบซ้ำ</div></div>;
  if (type === 'mapping') return <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-slate-700 text-slate-400"><th className="p-3">OWASP/CWE</th><th className="p-3">ตัวอย่างหลักฐาน JRE 2027</th><th className="p-3">แนวทาง</th></tr></thead><tbody className="divide-y divide-slate-800"><MapRow code="A01 / CWE-284" finding="RLS public policy และ client-side authorization" fix="owner/admin policy + server-side checks" /><MapRow code="A07 / CWE-640" finding="magic OTP และ fallback auth" fix="Supabase Auth + expiring one-time token" /><MapRow code="A02 / CWE-916" finding="SHA-256 รอบเดียวใน browser" fix="server-side password KDF" /><MapRow code="A06 / CWE-1321" finding="npm audit: xlsx prototype pollution" fix="update/replace dependency + CI gate" /></tbody></table></div>;
  if (type === 'remediation') return <div className="grid grid-cols-1 md:grid-cols-2 gap-3">{['1. Contain: ปิด public account payload และ rotate credential', '2. Auth: ลบ magic OTP/fallback และใช้ server auth', '3. Data: staging migration ผ่านแล้ว; ทำ authenticated owner/admin regression ก่อน production', '4. Code: filter registrations ตาม owner และล้าง state เมื่อ logout', '5. Supply chain: update dependencies + secret scan', '6. Retest: staging tests, screenshots, response logs, แล้วค่อย deploy'].map((item) => <div key={item} className="p-4 rounded-2xl bg-slate-950 border border-slate-800 text-sm text-slate-200 flex gap-2"><Wrench className="w-4 h-4 text-emerald-400 mt-0.5 shrink-0" />{item}</div>)}</div>;
  return <div className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><Highlight icon="A" title="เปิด URL" text="/presentation และ /security พร้อมอธิบาย scope/ethics" /><Highlight icon="B" title="แสดงหลักฐาน" text="build, npm audit, headers, Supabase field count (ไม่เปิด PII)" /><Highlight icon="C" title="สาธิต diagram" text="อธิบาย MCP เป็น context/tool layer ไม่ใช่ proof of fix" /><Highlight icon="D" title="สรุปต่ออาจารย์" text="ให้ remediation checklist และบอกข้อจำกัด Kali/DVWA อย่างตรงไปตรงมา" /></div><div className="p-4 rounded-2xl bg-slate-950 border border-slate-800 text-xs text-slate-400 leading-relaxed"><Terminal className="w-4 h-4 text-sky-400 inline mr-2" />คำสั่งหลักที่ทำซ้ำได้: <code className="text-amber-300">npm run build</code>, <code className="text-amber-300">npm audit --json</code>, ตรวจ HTTP headers และอ่าน Supabase metadata แบบ read-only</div></div>;
}

function Highlight({ icon, title, text }) { return <div className="p-4 rounded-2xl bg-slate-950 border border-slate-800"><span className="w-8 h-8 rounded-xl bg-indigo-500/20 text-indigo-300 flex items-center justify-center font-black">{icon}</span><h3 className="text-sm font-black text-white mt-3">{title}</h3><p className="text-xs text-slate-400 mt-1 leading-relaxed">{text}</p></div>; }
function Stat({ label, value, tone }) { const colors = { rose: 'border-rose-500/40 text-rose-300', orange: 'border-orange-500/40 text-orange-300', amber: 'border-amber-500/40 text-amber-300', sky: 'border-sky-500/40 text-sky-300' }; return <div className={`p-4 rounded-2xl bg-slate-950 border ${colors[tone]} text-center`}><div className="text-[10px] font-black uppercase">{label}</div><div className="text-3xl font-black text-white mt-1">{value}</div></div>; }
function MapRow({ code, finding, fix }) { return <tr><td className="p-3 font-mono text-amber-300 whitespace-nowrap">{code}</td><td className="p-3 text-slate-300">{finding}</td><td className="p-3 text-emerald-300">{fix}</td></tr>; }
